// src/app/layout.js

import Sidebar from '../components/Sidebar';
import '../app/globals.css';

export const metadata = {
  title: 'Create.xyz App',
  description: 'Generated by create.xyz',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
        <Sidebar />
        <main className="flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}
